# Generated by Django 4.2.7 on 2023-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentes',
            name='apellido',
            field=models.CharField(default='Perez', max_length=128),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referentes',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
