# Generated by Django 4.2.7 on 2023-11-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_referentes_apellido_alter_equipos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentes',
            name='apellido',
            field=models.CharField(max_length=128),
        ),
    ]
