# Generated by Django 4.2.7 on 2023-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_articulos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
