# Generated by Django 4.2.7 on 2023-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_articulos_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='referentes',
        ),
    ]
